### ISSUE TITLE
probando el post

### ISSUE THREAD

**Issue by mbfuster** [mbfuster/TelegramBot#40]
probandooo el comando /post en la recorreccion yei

**Comment by MavriBotUser** [comment]
<Belén Fuster desde Telegram>
alguna respuesta

**Comment by MavriBotUser** [comment]
<Belén Fuster desde Telegram>
por qué no te funciona? :'(

**Comment by MavriBotUser** [comment]
<Matías Junemann desde Telegram>
chai

**Comment by MavriBotUser** [comment]
<Juan Cortés desde Telegram>
hola :)

**Comment by MavriBotUser** [comment]
<Hernan Valdivieso desde Telegram>
hola

**Comment by MavriBotUser** [comment]
<Cristián Cortés desde Telegram>
eurokaa funciona!

**Comment by MavriBotUser** [comment]
<Belén Fuster desde Telegram>
quizas ahora?

**Comment by MavriBotUser** [comment]
<Guillermo Figueroa desde Telegram>
Y eso que estoy en usa (mentira, llegue hoy)

**Comment by MavriBotUser** [comment]
<Belén Fuster desde Telegram>
me fallaste ... y tanto amor que te puse .... T__T

**Comment by MavriBotUser** [comment]
<Ivania Donoso desde Telegram>
hola

**Comment by MavriBotUser** [comment]
<Ivania Donoso desde Telegram>
alskdjasldjas assdasda
